### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by szzz666** [MemoriesOfTime/TeamSystem#3]
核心是mot
下面是后台日志和视频

[server.log](https://github.com/MemoriesOfTime/TeamSystem/files/11671161/server.log)

https://github.com/MemoriesOfTime/TeamSystem/assets/60167194/7e8ffac0-c7f5-4c5e-80ab-12ca7e728322

**Comment by k7Xm9pQr** [comment]
你需要安装这个插件的前置：[FormDSL](https://github.com/MemoriesOfTime/FormDSL)

**Comment by szzz666** [comment]
抱歉抱歉没有认真看

**Comment by szzz666** [comment]
FullKotlinLib和KotlinLib有什么区别

**Comment by k7Xm9pQr** [comment]
> KotlinLib

FullKotlinLib 会更大（

**Comment by szzz666** [comment]
安装KotlinLib插件
使用tema命令报错
2023-06-08 22:20:31.603 [main] FATAL - Could not pass event 'cn.nukkit.event.player.PlayerFormRespondedEvent' to 'MemoriesOfTime-GameCore v1.6.10': null on cn.lanink.gamecore.form.WindowListener
2023-06-08 22:20:31.604 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:3370) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:117) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1343) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1084) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:1052) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:769) [Nukkit-MOT-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:82) [Nukkit-MOT-SNAPSHOT.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'
	at cn.lanink.teamsystem.team.TeamManager$showCreateForm$1$1.<init>(TeamManager.kt) ~[?:?]
	at cn.lanink.teamsystem.team.TeamManager$showCreateForm$1$1.<clinit>(TeamManager.kt) ~[?:?]
	at cn.lanink.teamsystem.team.TeamManager.showCreateForm(TeamManager.kt:286) ~[?:?]
	at cn.lanink.teamsystem.TeamSystem$Companion$showMainForm$1$1$1.invoke(TeamSystem.kt:72) ~[?:?]
	at cn.lanink.teamsystem.TeamSystem$Companion$showMainForm$1$1$1.invoke(TeamSystem.kt:71) ~[?:?]
	at cn.lanink.formdsl.dsl.ElementKt.onPlayerClick$lambda-0(element.kt:82) ~[?:?]
	at cn.lanink.gamecore.form.element.ResponseElementButton.callClicked(ResponseElementButton.java:34) ~[?:?]
	at cn.lanink.gamecore.form.windows.AdvancedFormWindowSimple.onEvent(AdvancedFormWindowSimple.java:75) ~[?:?]
	at cn.lanink.gamecore.form.WindowListener.onPlayerFormResponded(WindowListener.java:48) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[Nukkit-MOT-SNAPSHOT.jar:?]
	... 11 more

**Comment by k7Xm9pQr** [comment]
> kotlin.jvm.internal.MutablePropertyReference1Impl

TeamSystem 需要的是 FullKotlinLib，里面有更多支持 Kotlin 所提供的类（协程库+ORM），所以体积会更大，之前的回答并没有详细解释 FullKotlinLib 和 KotlinLib 区别

**Comment by szzz666** [comment]
FullKotlinLib可以代替KotlinLib吗

**Comment by szzz666** [comment]
能不能给一个FullKotlinLib的下载链接，我找不到

**Comment by k7Xm9pQr** [comment]
> FullKotlinLib可以代替KotlinLib吗

可以

**Comment by szzz666** [comment]
ok，感谢你
